#ファイルから文字を取り出す
f = open('data.txt')
s = f.read()
l = f.readlines()
print('=======================')
print(f)
print('=======================')
print(type(f))
print('=======================')
print(s)
print('=======================')
print(type(s))
print('=======================')
print(l)
print('=======================')
print(type(l))
f.close()

#ファイルに出力
f = open('sample.txt')
print(f.read())
f = open('sample.txt', mode='w')
f.write('aaa')
f.close()