`define INST_PC_S           0
`define INST_PC_E           15 
`define INST_COUNTER0_S     16
`define INST_COUNTER0_E     23
`define INST_COUNTER1_4_S   24
`define INST_COUNTER1_4_E   31
`define INST_COUNTER1_WE    32
`define INST_COUNTER2_WE    33
`define INST_COUNTER3_WE    34
`define INST_COUNTER4_WE    35
`define INST_JUMP_COUNTER1  36
`define INST_JUMP_COUNTER2  37
`define INST_JUMP_COUNTER3  38
`define INST_JUMP_COUNTER4  39
`define INST_WBUF_SEND      40
`define INST_WBUF_EN_CTRL_S 41
`define INST_WBUF_EN_CTRL_E 46
`define INST_RADDRX_WE      47
`define INST_RADDRX_S       48 
`define INST_RADDRX_E       63
`define INST_OUTPUT_SEND    64
`define INST_OUTPUT_EN_CTRL_S 65
`define INST_OUTPUT_EN_CTRL_E 70
`define INST_WADDRX_WE      71
`define INST_WADDRX_S       72
`define INST_WADDRX_E       87
`define INST_CONV_CAL       88
`define INST_RADDRW_WE      89
`define INST_RADDRW_S       90 
`define INST_RADDRW_E       105
`define INST_WBUF_SEND_POOL   106
`define INST_OUTPUT_SEND_POOL 107
